schema {
    query:Query
    mutation:Mutation
}
type Query{
   getPost(id:String!):Post
}
type Mutation{
    addPost(input:newPostInput!):Post
}

type Post{
    id:String!
    title:String!
    content:String!
}

input newPostInput{
    title:String!
    content:String!
}